### ISSUE TITLE
please change meta labels (e.g., "Chorus:") to italics of a somewhat smaller size

### ISSUE THREAD

**Issue by bhempel** [yCanta/yCanta#32]
When in presentation mode, labels like "Chorus:" or "Ending:" or "1:" appear in the same font and size as the song stanzas themselves.  These are different and of less importance than the words of the song, so I suggest we use an italics font of a somewhat smaller size to de-emphasize them.  It will also save a little bit of screen space that can be given to the words of the song.

**Comment by carlhemp** [comment]
fixed
